# Generated by Django 3.0.1 on 2020-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200225_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
